/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package event.logger;

import org.junit.Test;

import com.even.logger.util.EventReader;

import static org.junit.Assert.*;

public class EventLoggerTest {
    @Test public void testSomeLibraryMethod() {
        EventReader classUnderTest = new EventReader();
        assertTrue("someEventLoggerMethod should return 'true'", classUnderTest.someReaderMethod());
    }
}
